### ISSUE TITLE
if you have time

### ISSUE THREAD

**Issue by r31crusher** [Wando1423/Antario#18]
could you try to make a tank AA

**Comment by Wando1423** [comment]
I dont know what is a tank AA, so you'd have to give me some info about it.

**Comment by r31crusher** [comment]
Its just an AA where you cant hit the head.

**Comment by Wando1423** [comment]
Well, I dont know any aa like this that can fight over resolvers. The lby ones work half times, so the enemy can hit or miss completly, but it works only while stationary.

**Comment by Wando1423** [comment]
No answer for 3 days, closing.
