### ISSUE TITLE
./uload not working 

### ISSUE THREAD

**Issue by 2ez4tuX** [Wando1423/Antario#27]
Every time i try to unload hack it doesn't get uload and when i quit csgo from console it take 1-2 min for csgo to close can you please look at it.

**Comment by Wando1423** [comment]
Will take a closer look tommorow.

**Comment by 2ez4tuX** [comment]
https://pastebin.com/NAf061Ya

**Comment by VAC-is-shit** [comment]
Yes it's not working.

**Comment by Wando1423** [comment]
Try now. If ./update will not work, try redownloading with --recursive.

**Comment by Wando1423** [comment]
Fixed, closing.

**Comment by 2ez4tuX** [comment]
yep its working fine thanks :+1:
