### ISSUE TITLE
Revolver auto cock shoots

### ISSUE THREAD

**Issue by jensuss** [Wando1423/Antario#3]
It shoots all the time. lol.

**Comment by Wando1423** [comment]
Should be an issue only when your FPS is low. IF thats the case, just change in aimbot.cpp
`if (postponeFireReady > 0 && postponeFireReady < globalVars->curtime)`
to 
`if (postponeFireReady > 0 && postponeFireReady < (globalVars->curtime - 0.5f))`

**Comment by jensuss** [comment]
It didn't help :/

**Comment by Plasma2450** [comment]
Increase it then.

**Comment by certmemer** [comment]
jestes pizda a nie skoczek
