### ISSUE TITLE
almost doesn't shoot at all with hitscan on (every weapon)

### ISSUE THREAD

**Issue by slowwoox** [Wando1423/Antario#30]
it does shoot but when u only stay still and the enemy is not behind smth

**Comment by Wando1423** [comment]
About being behind something, thats normal.
Will take a closer look tommorow.

**Comment by slowwoox** [comment]
still there

**Comment by Wando1423** [comment]
Yep, I cant test when I'm at work unfortunately. Will look in 6 hours.

**Comment by slowwoox** [comment]
shots now but only if the bone u selected is visible ex: if u have aimbot on head it only shots the head if the head is behind smth u dont shot at all

**Comment by Wando1423** [comment]
Well, thats how hitscan works, it shoots only visible bones.
If you'd need, I can add later option for it to shoot through wall if any other bone is visible, but that would make no sense.
