### ISSUE TITLE
Kill Timeout is not working

### ISSUE THREAD

**Issue by VAC-is-shit** [Wando1423/Antario#32]
Still snap to other target after killing.

**Comment by Wando1423** [comment]
You need to have targetlock enabled for it to work for now. Will change it in the future.

**Comment by VAC-is-shit** [comment]
I still don't understand what stickyaim/targetlock is :^( It seems just like some latency on aimbot,and is not controllable.

**Comment by Wando1423** [comment]
Targetloc/stickyaim - Prevents you from snapping between targets. In other way, If you shoot enemy1, it will not snap to enemy2 until enemy1 dies or hides, even if enemy2 is closer to the crosshair.

Its visible when you shoot long range and have little bit higher fov.

**Comment by VAC-is-shit** [comment]
Thanks for your reply.
