### ISSUE TITLE
Compilation Warning

### ISSUE THREAD

**Issue by Mauladen** [Wando1423/Antario#42]
![Warning](http://i.imgur.com/fdeVpJg.png)

It says that these values will always be true

**Comment by Mauladen** [comment]
![Error](http://i.imgur.com/68ywwJ4.png)

I think this also applies to this warning

**Comment by Wando1423** [comment]
Pushed a new update, should work now.

**Comment by Mauladen** [comment]
![](http://i.imgur.com/ikHhyhn.png)

**Comment by Wando1423** [comment]
Fixed.

**Comment by Mauladen** [comment]
Thanks, everything works fine
If I find still bugs I'll write
