### ISSUE TITLE
Aimbot is dead

### ISSUE THREAD

**Issue by VAC-is-shit** [Wando1423/Antario#53]
Just simply,doesn't work.

**Comment by VAC-is-shit** [comment]
This is my cute little config:
https://hastebin.com/ibuxixanem.json

**Comment by Krylov84** [comment]
"KillTimeout" : {
               "Enabled" : true,
               "Value" : 1
            },

Nothing else to say, except that you don't read anything there.

**Comment by VAC-is-shit** [comment]
YOU ARE GOD DAMNED RIGHT
