### ISSUE TITLE
Won't let me compile??

### ISSUE THREAD

**Issue by UnrealSkybox** [Wando1423/Antario#58]
Anyone else getting this? It won't let me compile this I tried using sudo and without sudo and it's still not working. It just stays like for awhile. I can use the official AimTux and use cmake or make it works just fine. Anyone know a fix?
![screenshot_20170526_163911](https://cloud.githubusercontent.com/assets/27027221/26513635/33f89090-4232-11e7-8d1b-cbc9205bc7ba.png)

**Comment by Wando1423** [comment]
Hey, use ./build instead of "sudo ./build", should work then.

**Comment by Mauladen** [comment]
Everything works fine, you have specific problems

**Comment by UnrealSkybox** [comment]
i tried with and without sudo and deleted and reinstalled the files and atill didnt work

**Comment by Mauladen** [comment]
There really is a problem with cmake

**Comment by Krylov84** [comment]
Since a few commits it happened

**Comment by exp111** [comment]
I don't know how I fixed it but today it worked after checking the gcc version. 
Don't think that would do anything to it so probably just try over and over again?

**Comment by Krylov84** [comment]
After trying the first time, a retry makes it work.

**Comment by UnrealSkybox** [comment]
@Wando1423 Mauladen Whatever you did you fixed it but removing the script thingy. Now it works like perfectly.
