### ISSUE TITLE
Error while compiling Antiaim.cpp

### ISSUE THREAD

**Issue by fobbry** [Wando1423/Antario#7]
[  5%] Building CXX object CMakeFiles/Antario.dir/src/Hacks/antiaim.cpp.o
/home/fobbry/Antario/src/Hacks/antiaim.cpp: In function ‘void DoAntiAimY(QAngle&, int, bool, bool&)’:
/home/fobbry/Antario/src/Hacks/antiaim.cpp:197:23: error: jump to case label [-fpermissive]
   case AntiAimType_Y::LISP:
                       ^~~~
/home/fobbry/Antario/src/Hacks/antiaim.cpp:173:18: note:   crosses initialization of ‘C_BasePlayer* player’
    C_BasePlayer* player = ((C_BasePlayer*) entityList->GetClientEntity(engine->GetLocalPlayer()));
                  ^~~~~~
/home/fobbry/Antario/src/Hacks/antiaim.cpp:201:23: error: jump to case label [-fpermissive]
   case AntiAimType_Y::LISP_SIDE:
                       ^~~~~~~~~
/home/fobbry/Antario/src/Hacks/antiaim.cpp:173:18: note:   crosses initialization of ‘C_BasePlayer* player’
    C_BasePlayer* player = ((C_BasePlayer*) entityList->GetClientEntity(engine->GetLocalPlayer()));
                  ^~~~~~
/home/fobbry/Antario/src/Hacks/antiaim.cpp:214:23: error: jump to case label [-fpermissive]
   case AntiAimType_Y::LISP_JITTER:
                       ^~~~~~~~~~~
/home/fobbry/Antario/src/Hacks/antiaim.cpp:173:18: note:   crosses initialization of ‘C_BasePlayer* player’
    C_BasePlayer* player = ((C_BasePlayer*) entityList->GetClientEntity(engine->GetLocalPlayer()));
                  ^~~~~~
/home/fobbry/Antario/src/Hacks/antiaim.cpp:233:23: error: jump to case label [-fpermissive]
   case AntiAimType_Y::ANGEL_BACKWARD:
                       ^~~~~~~~~~~~~~
/home/fobbry/Antario/src/Hacks/antiaim.cpp:173:18: note:   crosses initialization of ‘C_BasePlayer* player’
    C_BasePlayer* player = ((C_BasePlayer*) entityList->GetClientEntity(engine->GetLocalPlayer()));
                  ^~~~~~
/home/fobbry/Antario/src/Hacks/antiaim.cpp:237:23: error: jump to case label [-fpermissive]
   case AntiAimType_Y::ANGEL_INVERSE:
                       ^~~~~~~~~~~~~
/home/fobbry/Antario/src/Hacks/antiaim.cpp:173:18: note:   crosses initialization of ‘C_BasePlayer* player’
    C_BasePlayer* player = ((C_BasePlayer*) entityList->GetClientEntity(engine->GetLocalPlayer()));
                  ^~~~~~
/home/fobbry/Antario/src/Hacks/antiaim.cpp:241:23: error: jump to case label [-fpermissive]
   case AntiAimType_Y::ANGEL_SPIN:
                       ^~~~~~~~~~
/home/fobbry/Antario/src/Hacks/antiaim.cpp:173:18: note:   crosses initialization of ‘C_BasePlayer* player’
    C_BasePlayer* player = ((C_BasePlayer*) entityList->GetClientEntity(engine->GetLocalPlayer()));
                  ^~~~~~
/home/fobbry/Antario/src/Hacks/antiaim.cpp:95:9: warning: enumeration value ‘LISP’ not handled in switch [-Wswitch]
  switch (aa_type)
         ^
/home/fobbry/Antario/src/Hacks/antiaim.cpp:95:9: warning: enumeration value ‘LISP_SIDE’ not handled in switch [-Wswitch]
/home/fobbry/Antario/src/Hacks/antiaim.cpp:95:9: warning: enumeration value ‘LISP_JITTER’ not handled in switch [-Wswitch]
/home/fobbry/Antario/src/Hacks/antiaim.cpp:95:9: warning: enumeration value ‘ANGEL_BACKWARD’ not handled in switch [-Wswitch]
/home/fobbry/Antario/src/Hacks/antiaim.cpp:95:9: warning: enumeration value ‘ANGEL_INVERSE’ not handled in switch [-Wswitch]
/home/fobbry/Antario/src/Hacks/antiaim.cpp:95:9: warning: enumeration value ‘ANGEL_SPIN’ not handled in switch [-Wswitch]

**Comment by Wando1423** [comment]
Well, I still dont recommend using it as its probably still detected, but try now.
