### ISSUE TITLE
Third person issue

### ISSUE THREAD

**Issue by gituser29** [Wando1423/Antario#78]
Third person seems to not work at all.

I hooked OverrideView and used the code from this thread
> https://www.unknowncheats.me/forum/counterstrike-global-offensive/193273-thirdperson-spoofing-sv_cheats.html

I also hooked fsn and switched to a different input class and neither returned positive results.

edit: I made sure g_Input was working as intended, I'm out of ideas.

**Comment by Wando1423** [comment]
Having no issues on 2 different sources using that base, not related.
Closing.

**Comment by gituser29** [comment]
Do you mind showing your code then? Someone else on uc is having the same exact problem with this base.

**Comment by Wando1423** [comment]
```
if (shouldThirdperson)
{
	Ray_t ray;
	trace_t tr;
	float adjDist = g_Settings.thirdperson.flDistance;
	Vector origin = pLocal->GetEyePosition();
	CTraceFilter filter;
	filter.pSkip = pLocal;

	Vector forward;
	Math::AngleVectors(vecAngles, &forward);

	ray.Init(origin, origin - (forward * g_Settings.thirdperson.flDistance), CAM_HULL_MIN, CAM_HULL_MAX);
	g_pEngineTrace->TraceRay(ray, MASK_SOLID, &filter, &tr);

	if (tr.fraction < 1.0)
		adjDist = g_Settings.thirdperson.flDistance * tr.fraction;

	if (adjDist < 16.0)
		adjDist = 16.0;

	g_pInput->m_fCameraInThirdPerson = true;
	g_pInput->m_vecCameraOffset = Vector(vecAngles.x, vecAngles.y, adjDist);
}
else
{
	g_pInput->m_fCameraInThirdPerson = false;
	g_pInput->m_vecCameraOffset = Vector(vecAngles.x, vecAngles.y, 0);
}
```

**Comment by gituser29** [comment]
Issue still persist. Thanks for trying to help me though. I'll try fixing it soon.
